### PR TITLE
Updated English localization file; Added Russian localization

### PR DESCRIPTION
**Pull request by Satton2**
• Some improvements and fixes to the English localization file.
• Added Russian localization file.

### CODE REVIEW

**Comment by Satton2** [comment]
Ah... I messed up in my first pull request, but I guess everything is fine in this one.

**Comment by Satton2** [comment]
Is there some reason to have the word "successfully" in this string?
`"You successfully made a fake equipment purchase!"`
In my opinion, there no need for it, but maybe I just forgot something that explains why people add this word that often in English.

**Review by Histalek — APPROVED** [review]
Nice!
As for the `successfully` bit: as you said it is not really necessary but it emphasizes on the success of the fakebuy. I personally wouldn't change it

**Comment by Satton2** [comment]
> Nice!
> As for the `successfully` bit: as you said it is not really necessary but it emphasizes on the success of the fakebuy. I personally wouldn't change it

But there is no unsuccessful way to make it, right? That means that it is completely unnecessary to keep it.
Of course, if there will be no approval about deleting "successfully" from the string, I will forget about it and will delete it only in the Russian localization file (what I already did).

**Pull request merged**
